configure: use DISTDIR and MASTERDIR params instead of a configuration file.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,26 +1,30 @@
 #!/bin/sh
-echo "Loading xbps-src configuration..."
-CFG=
-if [ -f "$1" ]; then
-	CFG="$1"
-elif [ -f "/etc/xbps/xbps-src.conf" ]; then
-	CFG="/etc/xbps/xbps-src.conf"
-elif [ -f "/usr/local/etc/xbps/xbps-src.conf" ]; then
-	CFG="/usr/local/etc/xbps/xbps-src.conf"
-else
-	echo "ERROR: You need to have xbps-src installed."
-	echo "Get it from https://github.com/xtraeme/xbps-src"
-	exit 1;
-fi
-. $CFG
-SRCPKGS=$XBPS_DISTDIR/srcpkgs
+#echo "Loading xbps-src configuration..."
+#CFG=
+#if [ -f "$1" ]; then
+#	CFG="$1"
+#elif [ -f "/etc/xbps/xbps-src.conf" ]; then
+#	CFG="/etc/xbps/xbps-src.conf"
+#elif [ -f "/usr/local/etc/xbps/xbps-src.conf" ]; then
+#	CFG="/usr/local/etc/xbps/xbps-src.conf"
+#else
+#	echo "ERROR: You need to have xbps-src installed."
+#	echo "Get it from https://github.com/xtraeme/xbps-src"
+#	exit 1;
+#fi
+#. $CFG
+#SRCPKGS=$XBPS_DISTDIR/srcpkgs
+DISTDIR=$1
+MASTERDIR=$2
+SRCPKGS=$DISTDIR/srcpkgs
 
 echo "Getting list of updates, please wait..."
 if [ -f "repo-checkvers.txt" ]; then
 	echo "(using cache; rm 'repo-checkvers.txt' to recheck)..."
 else
 	echo "Progress will not be shown. Please wait...."
-	xbps-src -c $CFG repo-checkvers > repo-checkvers.txt
+	xbps-src -D $DISTDIR -m $MASTERDIR repo-checkvers \
+		> repo-checkvers.txt
 	[ $? -gt 0 ] && exit 1
 	echo "end_of_file" >> repo-checkvers.txt
 fi
@@ -78,7 +82,7 @@ echo "print_pkgs:"						>> Makefile
 echo "\t@echo \$(PKGS)\n"					>> Makefile
 echo "built/%: tobuild/%"					>> Makefile
 echo "\t@echo \"[xbps-src]\t\${@F}\""				>> Makefile
-echo "\t@xbps-src -c $CFG build-pkg \${@F}"			>> Makefile
+echo "\t@xbps-src -D $DISTDIR -m $MASTERDIR build-pkg \${@F}"	>> Makefile
 echo "\t@touch \$@"						>> Makefile
 echo "\t@rm tobuild/\${@F}\n"					>> Makefile
 
@@ -86,7 +90,7 @@ echo "Finding and adding dependencies..."
 echo "# Dependencies"						>> Makefile
 for p in $TOBUILD; do
 	sedcmd="s|[<>].*\$||g"
-	_deps="`xbps-src -c $CFG show-deps $p build | sed -e \"$sedcmd\"`"
+	_deps="`xbps-src -D $DISTDIR -m $MASTERDIR show-deps $p build | sed -e \"$sedcmd\"`"
 	deps=
 	for d in $_deps; do
 		found=0
